<a href="https://colab.research.google.com/github/AnjaliMali1111/BIG-DATA-ANALYSIS/blob/main/Copy_of_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install dask
import dask.dataframe as dd
import pandas as pd
from google.colab import files

Requirement already satisfied: dask in /usr/local/lib/python3.11/dist-packages (2024.10.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/dist-packages (from dask) (8.1.8)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from dask) (3.1.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.11/dist-packages (from dask) (2024.10.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from dask) (24.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from dask) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from dask) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from dask) (0.12.1)
Requirement already satisfied: importlib-metadata>=4.13.0 in /usr/local/lib/python3.11/dist-packages (from dask) (8.6.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata>=4.13.0->dask) (3.21.0)
Requirement already satisfied: locket in /usr/local/lib/python3.11/dist-packages (from partd>=1.4.0->dask) (1.0.0)

/usr/local/lib/python3.11/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Classroom/12 th dilligent 1st/dataset(Task1). csv', encoding='latin-1') # Or try 'ISO-8859-1' if 'latin-1' doesn't work

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12-01-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12-01-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12-01-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12-01-2010 08:26,3.39,17850.0,United Kingdom

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [ ]:
print(f"Number of Rows:{len(df)} ")
print("Columns :",df.columns)

Number of Rows:541909
Columns : Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [ ]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [ ]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
import time
import pandas as pd #Importing pandas explicitly since it is not imported in this cell

start_time = time.time()

file_path = '/content/drive/MyDrive/Classroom/12 th dilligent 1st/dataset(Task1). csv' # Defining file_path
df_pandas = pd.read_csv(file_path, encoding='ISO-8859-1') # Added encoding
df_pandas["new_column"] = df_pandas[df_pandas.columns[0]] * 2  # Example operation

end_time = time.time()
print(f"Pandas Execution Time: {end_time - start_time:.2f} seconds")

Pandas Execution Time: 1.23 seconds

In [ ]:
import time
import dask.dataframe as dd
import pandas as pd

start_time = time.time()

file_path = '/content/drive/MyDrive/Classroom/12 th dilligent 1st/dataset(Task1). csv'
# Load the csv using dask.
# Specify dtypes to avoid type inference issues, use float64 for numerical columns and object for strings
df_dask = dd.read_csv(
    file_path,
    encoding='ISO-8859-1',
    dtype={'InvoiceNo': 'object',
           'StockCode': 'object',
           'Description': 'object',
           'Quantity': 'int64',
           'InvoiceDate': 'object',
           'UnitPrice': 'float64',
           'CustomerID':'float64',
           'Country':'object'})

# Example operation (make it a more complex operation so we can see potential dask benefits)
# Example: apply a function to a column
df_dask["new_column"] = df_dask['UnitPrice'] * df_dask['Quantity']

# Use a smaller computation to show that the .compute() call is what takes so long
df_dask_sample = df_dask.head()
# Compute a sample, this is much faster than computing everything

end_time = time.time()
print(f"Dask Execution Time: {end_time - start_time:.2f} seconds")

Dask Execution Time: 1.27 seconds

In [ ]:
df_dask.npartitions  # Shows how many partitions Dask has created

1

In [ ]:
result = df_dask.groupby(df_dask.columns[0]).mean(numeric_only=True).compute()
print(result)

               Quantity   UnitPrice  CustomerID      TotalCost  \
InvoiceNo
536365         5.714286    3.910000     17850.0      19.874286
536366         6.000000    1.850000     17850.0      11.100000
536367         6.916667    4.853333     13047.0      23.227500
536368         3.750000    4.775000     13047.0      17.512500
536369         3.000000    5.950000     13047.0      17.850000
...                 ...         ...         ...            ...
C581484   -80995.000000    2.080000     16446.0 -168469.600000
C581490      -11.500000    1.390000     14397.0     -16.265000
C581499       -1.000000  224.690000     15498.0    -224.690000
C581568       -5.000000   10.950000     15311.0     -54.750000
C581569       -3.000000    1.250000     17315.0      -3.750000

           TransformedCost
InvoiceNo
536365        4.062253e+02
536366        1.232100e+02
536367        6.805570e+02
536368        3.279544e+02
536369        3.186225e+02
...                    ...
C581484       2.838201e+10
C581490       3.154584e+02
C581499       5.048560e+04
C581568       2.997562e+03
C581569       2.031250e+01

[25900 rows x 5 columns]

In [ ]:
import pandas as pd
import dask.dataframe as dd
from google.colab import files


df_large = pd.concat([df_pandas] * 10, ignore_index=True)  # Increase data size
output_file_path = "/content/large_dataset.csv"  # Changed output path to /content
df_large.to_csv(output_file_path, index=False)

# Reload in Dask
df_dask_large = dd.read_csv(output_file_path)

In [ ]:
import pandas as pd
import dask.dataframe as dd
from google.colab import files
import time

df_large = pd.concat([df_pandas] * 10, ignore_index=True)  # Increase data size
output_file_path = "/content/large_dataset.csv"  # Changed output path to /content
df_large.to_csv(output_file_path, index=False)

# Reload in Dask
df_dask_large = dd.read_csv(output_file_path, dtype={
    'InvoiceNo': 'object',
    'StockCode': 'object',
    'Description': 'object',
    'Quantity': 'int64',
    'InvoiceDate': 'object',
    'UnitPrice': 'float64',
    'CustomerID': 'float64',
    'Country': 'object',
    'new_column':'object'
})


start_time = time.time()
df_pandas_large = pd.read_csv("/content/large_dataset.csv") # Updated the path
end_time = time.time()
print(f"Pandas Large Dataset Time: {end_time - start_time:.2f} seconds")

start_time = time.time()
df_dask_large.compute()
end_time = time.time()
print(f"Dask Large Dataset Time: {end_time - start_time:.2f} seconds")

Pandas Large Dataset Time: 10.64 seconds
Dask Large Dataset Time: 11.89 seconds

In [ ]:
from dask.diagnostics import ProgressBar
import dask.dataframe as dd
import pandas as pd

# Assuming df_dask_large is already defined from previous cells.
# If not, recreate it like this:
df_large = pd.concat([df_pandas] * 10, ignore_index=True)
output_file_path = "/content/large_dataset.csv"
df_large.to_csv(output_file_path, index=False)
df_dask_large = dd.read_csv(output_file_path, dtype={
    'InvoiceNo': 'object',
    'StockCode': 'object',
    'Description': 'object',
    'Quantity': 'int64',
    'InvoiceDate': 'object',
    'UnitPrice': 'float64',
    'CustomerID': 'float64',
    'Country': 'object',
    'new_column':'object'
})

with ProgressBar():
    result = df_dask_large.groupby(df_dask_large.columns[0]).mean(numeric_only=True).compute()
print(result)

[########################################] | 100% Completed | 13.95 s
               Quantity   UnitPrice  CustomerID
InvoiceNo
536365         5.714286    3.910000     17850.0
536366         6.000000    1.850000     17850.0
536367         6.916667    4.853333     13047.0
536368         3.750000    4.775000     13047.0
536369         3.000000    5.950000     13047.0
...                 ...         ...         ...
C581484   -80995.000000    2.080000     16446.0
C581490      -11.500000    1.390000     14397.0
C581499       -1.000000  224.690000     15498.0
C581568       -5.000000   10.950000     15311.0
C581569       -3.000000    1.250000     17315.0

[25900 rows x 3 columns]

In [ ]:
from dask.diagnostics import ProgressBar

with ProgressBar():
    df_dask_large.groupby(df_dask_large.columns[0]).mean(numeric_only=True).compute()

[########################################] | 100% Completed | 26.64 s

In [ ]:
import psutil

print(f"Pandas Memory Usage: {df_pandas.memory_usage().sum() / 1e6} MB")
print(f"Dask Memory Usage (per partition): {df_dask.map_partitions(lambda df: df.memory_usage().sum()).compute().sum() / 1e6} MB")

Pandas Memory Usage: 39.01758 MB
Dask Memory Usage (per partition): 79.53223 MB